# Generated by Django 4.0.4 on 2022-05-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_address_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
